-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 17:51:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorFrete` DECIMAL(6,2) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf_cnpj`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `localDep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empregado` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `ctps` VARCHAR(45) NOT NULL,
  `dataAdm` DATETIME NOT NULL,
  `dataDem` DATETIME NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `comissao` DECIMAL(6,2) NULL,
  `bonificacao` DECIMAL(6,2) NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NULL,
  `corresponsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `numero` VARCHAR(11) NOT NULL,
  `Fornecedor_cpf_cnpj` VARCHAR(14) NOT NULL,
  `Departamento_idDepartamento1` INT NOT NULL,
  `Empregado_cpf` VARCHAR(14) NOT NULL,
  `Cliente_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Fornecedor_idx` (`Fornecedor_cpf_cnpj` ASC) VISIBLE,
  INDEX `fk_Telefone_Departamento1_idx` (`Departamento_idDepartamento1` ASC) VISIBLE,
  INDEX `fk_Telefone_Empregado1_idx` (`Empregado_cpf` ASC) VISIBLE,
  INDEX `fk_Telefone_Cliente1_idx` (`Cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Fornecedor`
    FOREIGN KEY (`Fornecedor_cpf_cnpj`)
    REFERENCES `mydb`.`Fornecedor` (`cpf_cnpj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento1`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_Empregado1`
    FOREIGN KEY (`Empregado_cpf`)
    REFERENCES `mydb`.`Empregado` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `status_entrega` VARCHAR(20) NOT NULL,
  `comissao` DECIMAL(6,2) NULL,
  `desconto` DECIMAL(6,2) NULL,
  `Empregado_cpf` VARCHAR(14) NOT NULL,
  `Cliente_cpf` VARCHAR(14) NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Empregado1_idx` (`Empregado_cpf` ASC) VISIBLE,
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Empregado1`
    FOREIGN KEY (`Empregado_cpf`)
    REFERENCES `mydb`.`Empregado` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPgVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPgVenda` (
  `idFormaPgVenda` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valorPago` DECIMAL(7,2) NOT NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`idFormaPgVenda`),
  INDEX `fk_FormaPgVenda_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_FormaPgVenda_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `dataComp` DATETIME NOT NULL,
  `valortotal` DECIMAL(6,2) NOT NULL,
  `dataVenc` DATETIME NOT NULL,
  `dataPag` DATETIME NOT NULL,
  `desconto` DECIMAL(4,2) NULL,
  `juros` DECIMAL(5,2) NULL,
  `Fornecedor_cpf_cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Fornecedor1_idx` (`Fornecedor_cpf_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cpf_cnpj`)
    REFERENCES `mydb`.`Fornecedor` (`cpf_cnpj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPgCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPgCompra` (
  `idFormaPgCompra` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valorPago` DECIMAL(7,2) NOT NULL,
  `Compra_idCompra1` INT NOT NULL,
  PRIMARY KEY (`idFormaPgCompra`),
  INDEX `fk_FormaPgCompra_Compra1_idx` (`Compra_idCompra1` ASC) VISIBLE,
  CONSTRAINT `fk_FormaPgCompra_Compra1`
    FOREIGN KEY (`Compra_idCompra1`)
    REFERENCES `mydb`.`Compra` (`idCompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `data_entrada` DATE NOT NULL,
  `data_validade` DATE NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `data_atualizacao` DATE NOT NULL,
  `data_saida` DATE NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` DECIMAL(6,2) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `dataVenc` DATE NULL,
  `cor` VARCHAR(10) NOT NULL,
  `valorVend` DECIMAL(6,2) NOT NULL,
  `tamanho` VARCHAR(10) NOT NULL,
  `precoCusro` DECIMAL(6,2) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `Estoque_idEstoque` INT NULL,
  PRIMARY KEY (`idProdutos`),
  INDEX `fk_Produtos_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `Cliente_cpf` VARCHAR(14) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `comp` VARCHAR(45) NULL,
  `cep` CHAR(9) NOT NULL,
  `Fornecedor_cpf_cnpj` VARCHAR(14) NOT NULL,
  INDEX `fk_Endereco_Cliente1_idx` (`Cliente_cpf` ASC) VISIBLE,
  INDEX `fk_Endereco_Fornecedor1_idx` (`Fornecedor_cpf_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Endereco_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cpf_cnpj`)
    REFERENCES `mydb`.`Fornecedor` (`cpf_cnpj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itensVendaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itensVendaProd` (
  `Venda_idVenda` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  `quantidade` DECIMAL(6,2) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `desconto` DECIMAL(4,2) NULL,
  PRIMARY KEY (`Venda_idVenda`, `Produtos_idProdutos`),
  INDEX `fk_Venda_has_Produtos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_Venda_has_Produtos_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_has_Produtos_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `cbo` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `faixaSalarial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cbo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabalhar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabalhar` (
  `Departamento_idDepartamento` INT NOT NULL,
  `Empregado_cpf` VARCHAR(14) NOT NULL,
  `Cargo_cbo` INT NOT NULL,
  PRIMARY KEY (`Departamento_idDepartamento`, `Empregado_cpf`, `Cargo_cbo`),
  INDEX `fk_Departamento_has_Empregado_Empregado1_idx` (`Empregado_cpf` ASC) VISIBLE,
  INDEX `fk_Departamento_has_Empregado_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  INDEX `fk_Departamento_has_Empregado_Cargo1_idx` (`Cargo_cbo` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_has_Empregado_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Departamento_has_Empregado_Empregado1`
    FOREIGN KEY (`Empregado_cpf`)
    REFERENCES `mydb`.`Empregado` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Departamento_has_Empregado_Cargo1`
    FOREIGN KEY (`Cargo_cbo`)
    REFERENCES `mydb`.`Cargo` (`cbo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependentes` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `parentesco` VARCHAR(20) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `Empregado_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Dependentes_Empregado1_idx` (`Empregado_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_Empregado1`
    FOREIGN KEY (`Empregado_cpf`)
    REFERENCES `mydb`.`Empregado` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promocao` (
  `idPromocao` INT NOT NULL,
  `nomePromocao` VARCHAR(45) NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `percentualDesconto` DECIMAL(3,2) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AplicarPromocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AplicarPromocao` (
  `Produtos_idProdutos` INT NOT NULL,
  `Promocao_idPromocao` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`Produtos_idProdutos`, `Promocao_idPromocao`, `Estoque_idEstoque`),
  INDEX `fk_Produtos_has_Promocao_Promocao1_idx` (`Promocao_idPromocao` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Promocao_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_AplicarPromocao_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Promocao_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produtos_has_Promocao_Promocao1`
    FOREIGN KEY (`Promocao_idPromocao`)
    REFERENCES `mydb`.`Promocao` (`idPromocao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AplicarPromocao_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
